package com.ingramcontent.dataverse.utility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Constant implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Constant() {
    }

    public static String PRODUCT_ALL_TIMS_POLAR = "product_all_tims_polar";
    public static String ITEM_LOAD = "ItemLoad";
    public static String PUBLISHER_LOAD = "PublisherLoad";
    public static String PRODUCT_ALL_CS_POLAR = "product_all_cs_polar";
    public static String PRODUCT_ALL_LSI_POLAR = "product_all_lsi_polar";
    public static String PUBLISHER_ALL_LSI_POLAR = "publisher_all_lsi_polar";
    public static String PUBLISHER_ALL_TIMS_POLAR = "publisher_all_tims_polar";
    public static String TEST_PLAN1_INITIAL_LOAD = "TestPlan1-InitialLoad";
    public static String TEST_PLAN2_DELTA_LOAD = "TestPlan2-DeltaLoad";
    public static String TEST_PLAN3_INITIAL_LOAD_AGAIN = "TestPlan3-InitialLoadAgain";
    public static String TEST_PLAN4_DATA_CHANGE = "TestPlan4-DataChange";
    public static String TEST_PLAN5_DELTA_LOAD_AND_NEW = "TestPlan5-DeltaLoadAndNew";
    public static String TEST_PLAN6_RENAME_FILE_IN_FLIGHT = "TestPlan6-RenameFileInFlight";
    public static String SALES_ALL_TIMS_POLAR = "sales_all_tims_polar";
    
    public static String PROD = "PROD";
    public static String XFRM = "XFRM";
    public static String CNSM = "CNSM";
    public static int ZERO = 0;
    public static boolean TRUE_VAL = true;

}