package com.ingramcontent.dataverse.utility;

import org.kie.api.runtime.process.ProcessContext;
import org.kie.api.runtime.process.WorkflowProcessInstance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContextUtility implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ContextUtility() {
    }

	public static Object getProcessVariable(ProcessContext context, String variable) {
		WorkflowProcessInstance instance = (WorkflowProcessInstance) context.getProcessInstance();
		return instance.getVariable(variable);		
	}
	
	public static void setProcessVariable(ProcessContext context, String variable, Object obj) {
		WorkflowProcessInstance instance = (WorkflowProcessInstance) context.getProcessInstance();
		instance.setVariable(variable, obj);
	}	
	
	public static long getInstanceId(ProcessContext context) {
		return context.getProcessInstance().getId();
	}

}