package com.ingramcontent.dataverse.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Consumer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String containerId;
	private java.lang.String createdDate;
	private java.lang.String dataverseProcessId;
	private java.lang.String pipelineCode;
	private java.lang.Long processId;
	private java.lang.String requestType;
	private java.lang.String signalName;
	private java.lang.String taskName;

	public Consumer() {
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public java.lang.String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(java.lang.String createdDate) {
		this.createdDate = createdDate;
	}

	public java.lang.String getDataverseProcessId() {
		return this.dataverseProcessId;
	}

	public void setDataverseProcessId(java.lang.String dataverseProcessId) {
		this.dataverseProcessId = dataverseProcessId;
	}

	public java.lang.String getPipelineCode() {
		return this.pipelineCode;
	}

	public void setPipelineCode(java.lang.String pipelineCode) {
		this.pipelineCode = pipelineCode;
	}

	public java.lang.Long getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.Long processId) {
		this.processId = processId;
	}

	public java.lang.String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(java.lang.String requestType) {
		this.requestType = requestType;
	}

	public java.lang.String getSignalName() {
		return this.signalName;
	}

	public void setSignalName(java.lang.String signalName) {
		this.signalName = signalName;
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public Consumer(java.lang.String containerId, java.lang.String createdDate,
			java.lang.String dataverseProcessId, java.lang.String pipelineCode,
			java.lang.Long processId, java.lang.String requestType,
			java.lang.String signalName, java.lang.String taskName) {
		this.containerId = containerId;
		this.createdDate = createdDate;
		this.dataverseProcessId = dataverseProcessId;
		this.pipelineCode = pipelineCode;
		this.processId = processId;
		this.requestType = requestType;
		this.signalName = signalName;
		this.taskName = taskName;
	}

}