package com.ingramcontent.dataverse.model;

import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataFilter implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DataFilter() {
    }

    private Map<String, String> input;
 
	public Map<String, String> getInput() {
		return input;
	}
 
	public void setInput(Map<String, String> input) {
		this.input = input;
	}

}