package com.ingramcontent.dataverse.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KafkaRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String kafka_key;
	private java.lang.String topic;
	private com.ingramcontent.dataverse.model.Message message;

	public KafkaRequest() {
	}

	public java.lang.String getKafka_key() {
		return this.kafka_key;
	}

	public void setKafka_key(java.lang.String kafka_key) {
		this.kafka_key = kafka_key;
	}

	public java.lang.String getTopic() {
		return this.topic;
	}

	public void setTopic(java.lang.String topic) {
		this.topic = topic;
	}

	public com.ingramcontent.dataverse.model.Message getMessage() {
		return this.message;
	}

	public void setMessage(com.ingramcontent.dataverse.model.Message message) {
		this.message = message;
	}

	public KafkaRequest(java.lang.String kafka_key, java.lang.String topic,
			com.ingramcontent.dataverse.model.Message message) {
		this.kafka_key = kafka_key;
		this.topic = topic;
		this.message = message;
	}

}