package com.ingramcontent.dataverse.model;

import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PipelineThreshold implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Map<String, Integer> threshold;
 
	public Map<String, Integer> getThreshold() {
		return threshold;
	}
 
	public void setThreshold(Map<String, Integer> threshold) {
		this.threshold = threshold;
	}
	
	public PipelineThreshold() {}
 
	public PipelineThreshold(Map<String, Integer> threshold) {
		super();
		this.threshold = threshold;
	}
 
}