package com.ingramcontent.dataverse.model;

import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Producer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long processId;
	private java.lang.String signalName;
	private java.lang.String pipelineCode;
	private java.lang.String taskName;
	private java.lang.String createdDate;

	private java.lang.String dataverseProcessId;

	private java.lang.String requestType;

	private java.lang.String containerId;
	private Map<String, String> dataFilter;
	

	public Producer() {
	}

	public java.lang.Long getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.Long processId) {
		this.processId = processId;
	}

	public java.lang.String getSignalName() {
		return this.signalName;
	}

	public void setSignalName(java.lang.String signalName) {
		this.signalName = signalName;
	}

	public java.lang.String getPipelineCode() {
		return this.pipelineCode;
	}

	public void setPipelineCode(java.lang.String pipelineCode) {
		this.pipelineCode = pipelineCode;
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public java.lang.String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(java.lang.String createdDate) {
		this.createdDate = createdDate;
	}

	public java.lang.String getDataverseProcessId() {
		return this.dataverseProcessId;
	}

	public void setDataverseProcessId(java.lang.String dataverseProcessId) {
		this.dataverseProcessId = dataverseProcessId;
	}

	public java.lang.String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(java.lang.String requestType) {
		this.requestType = requestType;
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}
	
	public Map<String, String> getDataFilter() {
		return dataFilter;
	}
 
	public void setDataFilter(Map<String, String> dataFilter) {
		this.dataFilter = dataFilter;
	}

	public Producer(java.lang.Long processId, java.lang.String signalName,
			java.lang.String pipelineCode, java.lang.String taskName,
			java.lang.String createdDate, java.lang.String dataverseProcessId,
			java.lang.String requestType, java.lang.String containerId) {
		this.processId = processId;
		this.signalName = signalName;
		this.pipelineCode = pipelineCode;
		this.taskName = taskName;
		this.createdDate = createdDate;
		this.dataverseProcessId = dataverseProcessId;
		this.requestType = requestType;
		this.containerId = containerId;
	}

}